# Site settings
title: quine.io
email: quine@quine.io
description: > # this means to ignore newlines until "baseurl:"
    A place to ramble about the things we build.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://quine.io" # the base hostname & protocol for your site
twitter_username: quine_io
github_username:  quine-io

# Build settings
markdown: kramdown
